// Mocks generated by Mockito 5.4.6 from annotations
// in yelauncher/test/integration_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yelauncher/data/repositories/content/content_repository.dart'
    as _i10;
import 'package:yelauncher/data/repositories/minecraft/minecraft_repository.dart'
    as _i2;
import 'package:yelauncher/data/repositories/mod_loader/mod_loader_repository.dart'
    as _i13;
import 'package:yelauncher/data/services/download_service.dart' as _i15;
import 'package:yelauncher/domain/models/content/content_item.dart' as _i11;
import 'package:yelauncher/domain/models/content/content_version.dart' as _i12;
import 'package:yelauncher/domain/models/download/download_model.dart' as _i16;
import 'package:yelauncher/domain/models/instance/instance_model.dart' as _i8;
import 'package:yelauncher/domain/models/minecraft/minecraft_process_model.dart'
    as _i9;
import 'package:yelauncher/domain/models/minecraft/minecraft_profile_model.dart'
    as _i5;
import 'package:yelauncher/domain/models/minecraft/minecraft_version_model.dart'
    as _i7;
import 'package:yelauncher/domain/models/mod_loader/mod_loader_version_model.dart'
    as _i14;
import 'package:yelauncher/utilities/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MinecraftRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMinecraftRepository extends _i1.Mock
    implements _i2.MinecraftRepository {
  @override
  _i3.Future<_i4.Result<List<_i5.MinecraftProfileModel>>> getProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getProfiles, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.MinecraftProfileModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.MinecraftProfileModel>>>(
                    this,
                    Invocation.method(#getProfiles, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i5.MinecraftProfileModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.MinecraftProfileModel>>>(
                    this,
                    Invocation.method(#getProfiles, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.MinecraftProfileModel>>>);

  @override
  _i3.Future<_i4.Result<_i5.MinecraftProfileModel?>> getSelectedProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedProfile, []),
            returnValue:
                _i3.Future<_i4.Result<_i5.MinecraftProfileModel?>>.value(
                  _i6.dummyValue<_i4.Result<_i5.MinecraftProfileModel?>>(
                    this,
                    Invocation.method(#getSelectedProfile, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i5.MinecraftProfileModel?>>.value(
                  _i6.dummyValue<_i4.Result<_i5.MinecraftProfileModel?>>(
                    this,
                    Invocation.method(#getSelectedProfile, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.MinecraftProfileModel?>>);

  @override
  _i3.Future<_i4.Result<void>> selectProfile(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#selectProfile, [uuid]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#selectProfile, [uuid]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#selectProfile, [uuid]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> removeProfile(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#removeProfile, [uuid]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeProfile, [uuid]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#removeProfile, [uuid]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.MinecraftProfileModel>> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue:
                _i3.Future<_i4.Result<_i5.MinecraftProfileModel>>.value(
                  _i6.dummyValue<_i4.Result<_i5.MinecraftProfileModel>>(
                    this,
                    Invocation.method(#authenticate, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i5.MinecraftProfileModel>>.value(
                  _i6.dummyValue<_i4.Result<_i5.MinecraftProfileModel>>(
                    this,
                    Invocation.method(#authenticate, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.MinecraftProfileModel>>);

  @override
  void cancelAuthentication() => super.noSuchMethod(
    Invocation.method(#cancelAuthentication, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i4.Result<List<_i7.MinecraftVersionModel>>> getVersions() =>
      (super.noSuchMethod(
            Invocation.method(#getVersions, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i7.MinecraftVersionModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i7.MinecraftVersionModel>>>(
                    this,
                    Invocation.method(#getVersions, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i7.MinecraftVersionModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i7.MinecraftVersionModel>>>(
                    this,
                    Invocation.method(#getVersions, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i7.MinecraftVersionModel>>>);

  @override
  _i3.Future<_i4.Result<void>> install(
    _i8.InstanceModel? instance, {
    void Function(int, int?)? onProgress,
    void Function(String)? onStepChanged,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #install,
              [instance],
              {#onProgress: onProgress, #onStepChanged: onStepChanged},
            ),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [instance],
                  {#onProgress: onProgress, #onStepChanged: onStepChanged},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [instance],
                  {#onProgress: onProgress, #onStepChanged: onStepChanged},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<bool>> isInstalled(_i8.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#isInstalled, [instance]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [instance]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [instance]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<String>> getJavaVersion(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getJavaVersion, [id]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i6.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#getJavaVersion, [id]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<String>>.value(
              _i6.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#getJavaVersion, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<_i9.MinecraftProcessModel>> run(
    _i8.InstanceModel? instance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#run, [instance]),
            returnValue:
                _i3.Future<_i4.Result<_i9.MinecraftProcessModel>>.value(
                  _i6.dummyValue<_i4.Result<_i9.MinecraftProcessModel>>(
                    this,
                    Invocation.method(#run, [instance]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i9.MinecraftProcessModel>>.value(
                  _i6.dummyValue<_i4.Result<_i9.MinecraftProcessModel>>(
                    this,
                    Invocation.method(#run, [instance]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.MinecraftProcessModel>>);

  @override
  _i3.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Result<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}

/// A class which mocks [ContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentRepository extends _i1.Mock implements _i10.ContentRepository {
  @override
  _i3.Future<_i4.Result<List<_i11.ContentItem>>> searchContent({
    required String? query,
    required String? projectType,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchContent, [], {
              #query: query,
              #projectType: projectType,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i11.ContentItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i11.ContentItem>>>(
                this,
                Invocation.method(#searchContent, [], {
                  #query: query,
                  #projectType: projectType,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i11.ContentItem>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i11.ContentItem>>>(
                    this,
                    Invocation.method(#searchContent, [], {
                      #query: query,
                      #projectType: projectType,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i11.ContentItem>>>);

  @override
  _i3.Future<_i4.Result<_i11.ContentItem>> getContent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getContent, [id]),
            returnValue: _i3.Future<_i4.Result<_i11.ContentItem>>.value(
              _i6.dummyValue<_i4.Result<_i11.ContentItem>>(
                this,
                Invocation.method(#getContent, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i11.ContentItem>>.value(
                  _i6.dummyValue<_i4.Result<_i11.ContentItem>>(
                    this,
                    Invocation.method(#getContent, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i11.ContentItem>>);

  @override
  _i3.Future<_i4.Result<List<_i12.ContentVersion>>> getVersions(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVersions, [id]),
            returnValue:
                _i3.Future<_i4.Result<List<_i12.ContentVersion>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i12.ContentVersion>>>(
                    this,
                    Invocation.method(#getVersions, [id]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i12.ContentVersion>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i12.ContentVersion>>>(
                    this,
                    Invocation.method(#getVersions, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i12.ContentVersion>>>);
}

/// A class which mocks [ModLoaderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockModLoaderRepository extends _i1.Mock
    implements _i13.ModLoaderRepository {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get icon =>
      (super.noSuchMethod(
            Invocation.getter(#icon),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#icon)),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#icon),
            ),
          )
          as String);

  @override
  _i3.Future<_i4.Result<List<_i14.ModLoaderVersionModel>>> getVersions(
    String? minecraftVersion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVersions, [minecraftVersion]),
            returnValue:
                _i3.Future<_i4.Result<List<_i14.ModLoaderVersionModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i14.ModLoaderVersionModel>>>(
                    this,
                    Invocation.method(#getVersions, [minecraftVersion]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i14.ModLoaderVersionModel>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i14.ModLoaderVersionModel>>>(
                    this,
                    Invocation.method(#getVersions, [minecraftVersion]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i14.ModLoaderVersionModel>>>);

  @override
  _i3.Future<_i4.Result<void>> install(
    String? id, {
    String? minecraftVersion,
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #install,
              [id],
              {#minecraftVersion: minecraftVersion, #onProgress: onProgress},
            ),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [id],
                  {
                    #minecraftVersion: minecraftVersion,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [id],
                  {
                    #minecraftVersion: minecraftVersion,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<bool>> isInstalled(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isInstalled, [id]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [id]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<void>> processInstallation(
    String? id,
    String? minecraftVersion, {
    String? javaExecutablePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processInstallation,
              [id, minecraftVersion],
              {#javaExecutablePath: javaExecutablePath},
            ),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #processInstallation,
                  [id, minecraftVersion],
                  {#javaExecutablePath: javaExecutablePath},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #processInstallation,
                  [id, minecraftVersion],
                  {#javaExecutablePath: javaExecutablePath},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<String>>> getLibrariesPath(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLibrariesPath, [id]),
            returnValue: _i3.Future<_i4.Result<List<String>>>.value(
              _i6.dummyValue<_i4.Result<List<String>>>(
                this,
                Invocation.method(#getLibrariesPath, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<String>>>.value(
                  _i6.dummyValue<_i4.Result<List<String>>>(
                    this,
                    Invocation.method(#getLibrariesPath, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<String>>>);
}

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i15.DownloadService {
  @override
  _i3.Future<_i4.Result<void>> download(
    _i16.DownloadModel? model, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [model], {#onProgress: onProgress}),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #download,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #download,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<bool>> isDownloaded(_i16.DownloadModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#isDownloaded, [model]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isDownloaded, [model]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isDownloaded, [model]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<void>> downloadIfMissing(
    _i16.DownloadModel? model, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadIfMissing,
              [model],
              {#onProgress: onProgress},
            ),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #downloadIfMissing,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #downloadIfMissing,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> downloadAll(
    List<_i16.DownloadModel>? models, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadAll,
              [models],
              {#onProgress: onProgress},
            ),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #downloadAll,
                  [models],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #downloadAll,
                  [models],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
