// Mocks generated by Mockito 5.4.6 from annotations
// in yelauncher/test/integration_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:yelauncher/data/repositories/content/content_repository.dart'
    as _i11;
import 'package:yelauncher/data/repositories/instances/instance_repository.dart'
    as _i19;
import 'package:yelauncher/data/repositories/minecraft/minecraft_repository.dart'
    as _i3;
import 'package:yelauncher/data/repositories/mod_loader/mod_loader_repository.dart'
    as _i14;
import 'package:yelauncher/data/repositories/settings/settings_repository.dart'
    as _i18;
import 'package:yelauncher/data/services/download_service.dart' as _i16;
import 'package:yelauncher/domain/models/content/content_item.dart' as _i12;
import 'package:yelauncher/domain/models/content/content_version.dart' as _i13;
import 'package:yelauncher/domain/models/download/download_model.dart' as _i17;
import 'package:yelauncher/domain/models/instance/instance_model.dart' as _i9;
import 'package:yelauncher/domain/models/minecraft/minecraft_process_model.dart'
    as _i10;
import 'package:yelauncher/domain/models/minecraft/minecraft_profile_model.dart'
    as _i6;
import 'package:yelauncher/domain/models/minecraft/minecraft_version_model.dart'
    as _i8;
import 'package:yelauncher/domain/models/mod_loader/mod_loader_version_model.dart'
    as _i15;
import 'package:yelauncher/utilities/result.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocale_0 extends _i1.SmartFake implements _i2.Locale {
  _FakeLocale_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MinecraftRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMinecraftRepository extends _i1.Mock
    implements _i3.MinecraftRepository {
  @override
  _i4.Future<_i5.Result<List<_i6.MinecraftProfileModel>>> getProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getProfiles, []),
            returnValue:
                _i4.Future<_i5.Result<List<_i6.MinecraftProfileModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i6.MinecraftProfileModel>>>(
                    this,
                    Invocation.method(#getProfiles, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i6.MinecraftProfileModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i6.MinecraftProfileModel>>>(
                    this,
                    Invocation.method(#getProfiles, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i6.MinecraftProfileModel>>>);

  @override
  _i4.Future<_i5.Result<_i6.MinecraftProfileModel?>> getSelectedProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedProfile, []),
            returnValue:
                _i4.Future<_i5.Result<_i6.MinecraftProfileModel?>>.value(
                  _i7.dummyValue<_i5.Result<_i6.MinecraftProfileModel?>>(
                    this,
                    Invocation.method(#getSelectedProfile, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<_i6.MinecraftProfileModel?>>.value(
                  _i7.dummyValue<_i5.Result<_i6.MinecraftProfileModel?>>(
                    this,
                    Invocation.method(#getSelectedProfile, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.MinecraftProfileModel?>>);

  @override
  _i4.Future<_i5.Result<void>> selectProfile(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#selectProfile, [uuid]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#selectProfile, [uuid]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#selectProfile, [uuid]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> removeProfile(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#removeProfile, [uuid]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#removeProfile, [uuid]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#removeProfile, [uuid]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<_i6.MinecraftProfileModel>> authenticate() =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, []),
            returnValue:
                _i4.Future<_i5.Result<_i6.MinecraftProfileModel>>.value(
                  _i7.dummyValue<_i5.Result<_i6.MinecraftProfileModel>>(
                    this,
                    Invocation.method(#authenticate, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<_i6.MinecraftProfileModel>>.value(
                  _i7.dummyValue<_i5.Result<_i6.MinecraftProfileModel>>(
                    this,
                    Invocation.method(#authenticate, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i6.MinecraftProfileModel>>);

  @override
  _i4.Future<_i5.Result<void>> addOfflineProfile(String? nickname) =>
      (super.noSuchMethod(
            Invocation.method(#addOfflineProfile, [nickname]),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#addOfflineProfile, [nickname]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#addOfflineProfile, [nickname]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  void cancelAuthentication() => super.noSuchMethod(
    Invocation.method(#cancelAuthentication, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.Result<List<_i8.MinecraftVersionModel>>> getVersions() =>
      (super.noSuchMethod(
            Invocation.method(#getVersions, []),
            returnValue:
                _i4.Future<_i5.Result<List<_i8.MinecraftVersionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i8.MinecraftVersionModel>>>(
                    this,
                    Invocation.method(#getVersions, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i8.MinecraftVersionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i8.MinecraftVersionModel>>>(
                    this,
                    Invocation.method(#getVersions, []),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i8.MinecraftVersionModel>>>);

  @override
  _i4.Future<_i5.Result<void>> install(
    _i9.InstanceModel? instance, {
    void Function(int, int?)? onProgress,
    void Function(String)? onStepChanged,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #install,
              [instance],
              {#onProgress: onProgress, #onStepChanged: onStepChanged},
            ),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [instance],
                  {#onProgress: onProgress, #onStepChanged: onStepChanged},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [instance],
                  {#onProgress: onProgress, #onStepChanged: onStepChanged},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<bool>> isInstalled(_i9.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#isInstalled, [instance]),
            returnValue: _i4.Future<_i5.Result<bool>>.value(
              _i7.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [instance]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<bool>>.value(
              _i7.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [instance]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool>>);

  @override
  _i4.Future<_i5.Result<String>> getJavaVersion(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getJavaVersion, [id]),
            returnValue: _i4.Future<_i5.Result<String>>.value(
              _i7.dummyValue<_i5.Result<String>>(
                this,
                Invocation.method(#getJavaVersion, [id]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<String>>.value(
              _i7.dummyValue<_i5.Result<String>>(
                this,
                Invocation.method(#getJavaVersion, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<String>>);

  @override
  _i4.Future<_i5.Result<_i10.MinecraftProcessModel>> run(
    _i9.InstanceModel? instance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#run, [instance]),
            returnValue:
                _i4.Future<_i5.Result<_i10.MinecraftProcessModel>>.value(
                  _i7.dummyValue<_i5.Result<_i10.MinecraftProcessModel>>(
                    this,
                    Invocation.method(#run, [instance]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<_i10.MinecraftProcessModel>>.value(
                  _i7.dummyValue<_i5.Result<_i10.MinecraftProcessModel>>(
                    this,
                    Invocation.method(#run, [instance]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i10.MinecraftProcessModel>>);

  @override
  _i4.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i5.Result<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(#logout, []),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}

/// A class which mocks [ContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentRepository extends _i1.Mock implements _i11.ContentRepository {
  @override
  _i4.Future<_i5.Result<List<_i12.ContentItem>>> searchContent({
    required String? query,
    required String? projectType,
    List<String>? versions = const [],
    List<String>? modLoaders = const [],
    List<String>? categories = const [],
    String? sortOrder = 'relevance',
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchContent, [], {
              #query: query,
              #projectType: projectType,
              #versions: versions,
              #modLoaders: modLoaders,
              #categories: categories,
              #sortOrder: sortOrder,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<_i5.Result<List<_i12.ContentItem>>>.value(
              _i7.dummyValue<_i5.Result<List<_i12.ContentItem>>>(
                this,
                Invocation.method(#searchContent, [], {
                  #query: query,
                  #projectType: projectType,
                  #versions: versions,
                  #modLoaders: modLoaders,
                  #categories: categories,
                  #sortOrder: sortOrder,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i12.ContentItem>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i12.ContentItem>>>(
                    this,
                    Invocation.method(#searchContent, [], {
                      #query: query,
                      #projectType: projectType,
                      #versions: versions,
                      #modLoaders: modLoaders,
                      #categories: categories,
                      #sortOrder: sortOrder,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i12.ContentItem>>>);

  @override
  _i4.Future<_i5.Result<_i12.ContentItem>> getContent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getContent, [id]),
            returnValue: _i4.Future<_i5.Result<_i12.ContentItem>>.value(
              _i7.dummyValue<_i5.Result<_i12.ContentItem>>(
                this,
                Invocation.method(#getContent, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<_i12.ContentItem>>.value(
                  _i7.dummyValue<_i5.Result<_i12.ContentItem>>(
                    this,
                    Invocation.method(#getContent, [id]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i12.ContentItem>>);

  @override
  _i4.Future<_i5.Result<List<_i13.ContentVersion>>> getVersions(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVersions, [id]),
            returnValue:
                _i4.Future<_i5.Result<List<_i13.ContentVersion>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i13.ContentVersion>>>(
                    this,
                    Invocation.method(#getVersions, [id]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i13.ContentVersion>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i13.ContentVersion>>>(
                    this,
                    Invocation.method(#getVersions, [id]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i13.ContentVersion>>>);

  @override
  _i4.Future<_i5.Result<_i13.ContentVersion>> getVersion(String? versionId) =>
      (super.noSuchMethod(
            Invocation.method(#getVersion, [versionId]),
            returnValue: _i4.Future<_i5.Result<_i13.ContentVersion>>.value(
              _i7.dummyValue<_i5.Result<_i13.ContentVersion>>(
                this,
                Invocation.method(#getVersion, [versionId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<_i13.ContentVersion>>.value(
                  _i7.dummyValue<_i5.Result<_i13.ContentVersion>>(
                    this,
                    Invocation.method(#getVersion, [versionId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<_i13.ContentVersion>>);

  @override
  _i4.Future<_i5.Result<List<_i12.ContentItem>>> getProjectDependencies(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProjectDependencies, [id]),
            returnValue: _i4.Future<_i5.Result<List<_i12.ContentItem>>>.value(
              _i7.dummyValue<_i5.Result<List<_i12.ContentItem>>>(
                this,
                Invocation.method(#getProjectDependencies, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i12.ContentItem>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i12.ContentItem>>>(
                    this,
                    Invocation.method(#getProjectDependencies, [id]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i12.ContentItem>>>);
}

/// A class which mocks [ModLoaderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockModLoaderRepository extends _i1.Mock
    implements _i14.ModLoaderRepository {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get icon =>
      (super.noSuchMethod(
            Invocation.getter(#icon),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#icon)),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#icon),
            ),
          )
          as String);

  @override
  _i4.Future<_i5.Result<List<_i15.ModLoaderVersionModel>>> getVersions(
    String? minecraftVersion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVersions, [minecraftVersion]),
            returnValue:
                _i4.Future<_i5.Result<List<_i15.ModLoaderVersionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i15.ModLoaderVersionModel>>>(
                    this,
                    Invocation.method(#getVersions, [minecraftVersion]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<_i15.ModLoaderVersionModel>>>.value(
                  _i7.dummyValue<_i5.Result<List<_i15.ModLoaderVersionModel>>>(
                    this,
                    Invocation.method(#getVersions, [minecraftVersion]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<_i15.ModLoaderVersionModel>>>);

  @override
  _i4.Future<_i5.Result<void>> install(
    String? id, {
    String? minecraftVersion,
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #install,
              [id],
              {#minecraftVersion: minecraftVersion, #onProgress: onProgress},
            ),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [id],
                  {
                    #minecraftVersion: minecraftVersion,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [id],
                  {
                    #minecraftVersion: minecraftVersion,
                    #onProgress: onProgress,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<bool>> isInstalled(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#isInstalled, [id]),
            returnValue: _i4.Future<_i5.Result<bool>>.value(
              _i7.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [id]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<bool>>.value(
              _i7.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [id]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool>>);

  @override
  _i4.Future<_i5.Result<void>> processInstallation(
    String? id,
    String? minecraftVersion, {
    String? javaExecutablePath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processInstallation,
              [id, minecraftVersion],
              {#javaExecutablePath: javaExecutablePath},
            ),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #processInstallation,
                  [id, minecraftVersion],
                  {#javaExecutablePath: javaExecutablePath},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #processInstallation,
                  [id, minecraftVersion],
                  {#javaExecutablePath: javaExecutablePath},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<List<String>>> getLibrariesPath(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getLibrariesPath, [id]),
            returnValue: _i4.Future<_i5.Result<List<String>>>.value(
              _i7.dummyValue<_i5.Result<List<String>>>(
                this,
                Invocation.method(#getLibrariesPath, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Result<List<String>>>.value(
                  _i7.dummyValue<_i5.Result<List<String>>>(
                    this,
                    Invocation.method(#getLibrariesPath, [id]),
                  ),
                ),
          )
          as _i4.Future<_i5.Result<List<String>>>);
}

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i16.DownloadService {
  @override
  _i4.Future<_i5.Result<void>> download(
    _i17.DownloadModel? model, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [model], {#onProgress: onProgress}),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #download,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #download,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<bool>> isDownloaded(_i17.DownloadModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#isDownloaded, [model]),
            returnValue: _i4.Future<_i5.Result<bool>>.value(
              _i7.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#isDownloaded, [model]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<bool>>.value(
              _i7.dummyValue<_i5.Result<bool>>(
                this,
                Invocation.method(#isDownloaded, [model]),
              ),
            ),
          )
          as _i4.Future<_i5.Result<bool>>);

  @override
  _i4.Future<_i5.Result<void>> downloadIfMissing(
    _i17.DownloadModel? model, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadIfMissing,
              [model],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #downloadIfMissing,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #downloadIfMissing,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> downloadAll(
    List<_i17.DownloadModel>? models, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadAll,
              [models],
              {#onProgress: onProgress},
            ),
            returnValue: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #downloadAll,
                  [models],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i5.Result<void>>.value(
              _i7.dummyValue<_i5.Result<void>>(
                this,
                Invocation.method(
                  #downloadAll,
                  [models],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i4.Future<_i5.Result<void>>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i18.SettingsRepository {
  @override
  _i2.Locale get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _FakeLocale_0(this, Invocation.getter(#currentLocale)),
            returnValueForMissingStub: _FakeLocale_0(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as _i2.Locale);

  @override
  int get javaMemory =>
      (super.noSuchMethod(
            Invocation.getter(#javaMemory),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get windowWidth =>
      (super.noSuchMethod(
            Invocation.getter(#windowWidth),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get windowHeight =>
      (super.noSuchMethod(
            Invocation.getter(#windowHeight),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  String get customJavaPath =>
      (super.noSuchMethod(
            Invocation.getter(#customJavaPath),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#customJavaPath),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#customJavaPath),
            ),
          )
          as String);

  @override
  String get jvmArguments =>
      (super.noSuchMethod(
            Invocation.getter(#jvmArguments),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#jvmArguments),
            ),
            returnValueForMissingStub: _i7.dummyValue<String>(
              this,
              Invocation.getter(#jvmArguments),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<void> setLocale(_i2.Locale? locale) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [locale]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setMinecraftSettings({
    required int? javaMemory,
    required int? windowWidth,
    required int? windowHeight,
    required String? customJavaPath,
    required String? jvmArguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setMinecraftSettings, [], {
              #javaMemory: javaMemory,
              #windowWidth: windowWidth,
              #windowHeight: windowHeight,
              #customJavaPath: customJavaPath,
              #jvmArguments: jvmArguments,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [InstanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstanceRepository extends _i1.Mock
    implements _i19.InstanceRepository {
  @override
  _i4.Future<List<_i9.InstanceModel>> getInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getInstances, []),
            returnValue: _i4.Future<List<_i9.InstanceModel>>.value(
              <_i9.InstanceModel>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i9.InstanceModel>>.value(
                  <_i9.InstanceModel>[],
                ),
          )
          as _i4.Future<List<_i9.InstanceModel>>);

  @override
  _i4.Future<void> saveInstance(_i9.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#saveInstance, [instance]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteInstance(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInstance, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> openFolder(_i9.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#openFolder, [instance]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> openLogsFolder(_i9.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#openLogsFolder, [instance]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createInstance(_i9.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#createInstance, [instance]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
