// Mocks generated by Mockito 5.4.6 from annotations
// in yelauncher/test/ui/content/view_models/content_screen_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yelauncher/data/repositories/content/content_repository.dart'
    as _i2;
import 'package:yelauncher/domain/models/content/content_item.dart' as _i5;
import 'package:yelauncher/domain/models/content/content_version.dart' as _i7;
import 'package:yelauncher/utilities/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentRepository extends _i1.Mock implements _i2.ContentRepository {
  MockContentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.ContentItem>>> searchContent({
    required String? query,
    required String? projectType,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchContent, [], {
              #query: query,
              #projectType: projectType,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.ContentItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.ContentItem>>>(
                this,
                Invocation.method(#searchContent, [], {
                  #query: query,
                  #projectType: projectType,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.ContentItem>>>);

  @override
  _i3.Future<_i4.Result<_i5.ContentItem>> getContent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getContent, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.ContentItem>>.value(
              _i6.dummyValue<_i4.Result<_i5.ContentItem>>(
                this,
                Invocation.method(#getContent, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.ContentItem>>);

  @override
  _i3.Future<_i4.Result<List<_i7.ContentVersion>>> getVersions(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVersions, [id]),
            returnValue: _i3.Future<_i4.Result<List<_i7.ContentVersion>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.ContentVersion>>>(
                this,
                Invocation.method(#getVersions, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.ContentVersion>>>);
}
