// Mocks generated by Mockito 5.4.6 from annotations
// in yelauncher/test/data/services/instance_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yelauncher/data/repositories/java/java_repository.dart' as _i10;
import 'package:yelauncher/data/services/api/minecraft_api_client.dart' as _i2;
import 'package:yelauncher/data/services/api/models/asset_index_file_api_model.dart'
    as _i9;
import 'package:yelauncher/data/services/api/models/version_api_model.dart'
    as _i7;
import 'package:yelauncher/data/services/api/models/version_manifest_api_model.dart'
    as _i5;
import 'package:yelauncher/data/services/api/models/version_requirements_api_model.dart'
    as _i8;
import 'package:yelauncher/utilities/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [MinecraftApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMinecraftApiClient extends _i1.Mock
    implements _i2.MinecraftApiClient {
  @override
  _i3.Future<_i4.Result<_i5.VersionManifestApiModel>> getManifest() =>
      (super.noSuchMethod(
            Invocation.method(#getManifest, []),
            returnValue:
                _i3.Future<_i4.Result<_i5.VersionManifestApiModel>>.value(
                  _i6.dummyValue<_i4.Result<_i5.VersionManifestApiModel>>(
                    this,
                    Invocation.method(#getManifest, []),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i5.VersionManifestApiModel>>.value(
                  _i6.dummyValue<_i4.Result<_i5.VersionManifestApiModel>>(
                    this,
                    Invocation.method(#getManifest, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.VersionManifestApiModel>>);

  @override
  _i3.Future<_i4.Result<_i7.VersionApiModel>> getVersion(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVersion, [id]),
            returnValue: _i3.Future<_i4.Result<_i7.VersionApiModel>>.value(
              _i6.dummyValue<_i4.Result<_i7.VersionApiModel>>(
                this,
                Invocation.method(#getVersion, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i7.VersionApiModel>>.value(
                  _i6.dummyValue<_i4.Result<_i7.VersionApiModel>>(
                    this,
                    Invocation.method(#getVersion, [id]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i7.VersionApiModel>>);

  @override
  _i3.Future<_i4.Result<_i8.VersionRequirementsApiModel>> getRequirements(
    _i7.VersionApiModel? version,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRequirements, [version]),
            returnValue:
                _i3.Future<_i4.Result<_i8.VersionRequirementsApiModel>>.value(
                  _i6.dummyValue<_i4.Result<_i8.VersionRequirementsApiModel>>(
                    this,
                    Invocation.method(#getRequirements, [version]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i8.VersionRequirementsApiModel>>.value(
                  _i6.dummyValue<_i4.Result<_i8.VersionRequirementsApiModel>>(
                    this,
                    Invocation.method(#getRequirements, [version]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.VersionRequirementsApiModel>>);

  @override
  _i3.Future<_i4.Result<_i9.AssetIndexFileApiModel>> getAssetIndex(
    String? url,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetIndex, [url]),
            returnValue:
                _i3.Future<_i4.Result<_i9.AssetIndexFileApiModel>>.value(
                  _i6.dummyValue<_i4.Result<_i9.AssetIndexFileApiModel>>(
                    this,
                    Invocation.method(#getAssetIndex, [url]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i9.AssetIndexFileApiModel>>.value(
                  _i6.dummyValue<_i4.Result<_i9.AssetIndexFileApiModel>>(
                    this,
                    Invocation.method(#getAssetIndex, [url]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.AssetIndexFileApiModel>>);
}

/// A class which mocks [JavaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockJavaRepository extends _i1.Mock implements _i10.JavaRepository {
  @override
  _i3.Future<_i4.Result<String>> getJavaExecutablePath(int? version) =>
      (super.noSuchMethod(
            Invocation.method(#getJavaExecutablePath, [version]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i6.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#getJavaExecutablePath, [version]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<String>>.value(
              _i6.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#getJavaExecutablePath, [version]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<void>> install(
    int? version, {
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#install, [version], {#onProgress: onProgress}),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [version],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(
                  #install,
                  [version],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<bool>> isInstalled(int? version) =>
      (super.noSuchMethod(
            Invocation.method(#isInstalled, [version]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [version]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<bool>>.value(
              _i6.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isInstalled, [version]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);
}
