// Mocks generated by Mockito 5.4.6 from annotations
// in yelauncher/test/ui/content/widgets/content_install_dialog_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:yelauncher/data/repositories/content/content_repository.dart'
    as _i5;
import 'package:yelauncher/data/repositories/instances/instance_repository.dart'
    as _i2;
import 'package:yelauncher/data/services/download_service.dart' as _i10;
import 'package:yelauncher/domain/models/content/content_item.dart' as _i7;
import 'package:yelauncher/domain/models/content/content_version.dart' as _i9;
import 'package:yelauncher/domain/models/download/download_model.dart' as _i11;
import 'package:yelauncher/domain/models/instance/instance_model.dart' as _i4;
import 'package:yelauncher/utilities/result.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [InstanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInstanceRepository extends _i1.Mock
    implements _i2.InstanceRepository {
  @override
  _i3.Future<List<_i4.InstanceModel>> getInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getInstances, []),
            returnValue: _i3.Future<List<_i4.InstanceModel>>.value(
              <_i4.InstanceModel>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.InstanceModel>>.value(
                  <_i4.InstanceModel>[],
                ),
          )
          as _i3.Future<List<_i4.InstanceModel>>);

  @override
  _i3.Future<void> saveInstance(_i4.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#saveInstance, [instance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteInstance(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInstance, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> openFolder(_i4.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#openFolder, [instance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> createInstance(_i4.InstanceModel? instance) =>
      (super.noSuchMethod(
            Invocation.method(#createInstance, [instance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ContentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContentRepository extends _i1.Mock implements _i5.ContentRepository {
  @override
  _i3.Future<_i6.Result<List<_i7.ContentItem>>> searchContent({
    required String? query,
    required String? projectType,
    List<String>? versions = const [],
    List<String>? modLoaders = const [],
    List<String>? categories = const [],
    String? sortOrder = 'relevance',
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchContent, [], {
              #query: query,
              #projectType: projectType,
              #versions: versions,
              #modLoaders: modLoaders,
              #categories: categories,
              #sortOrder: sortOrder,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<_i6.Result<List<_i7.ContentItem>>>.value(
              _i8.dummyValue<_i6.Result<List<_i7.ContentItem>>>(
                this,
                Invocation.method(#searchContent, [], {
                  #query: query,
                  #projectType: projectType,
                  #versions: versions,
                  #modLoaders: modLoaders,
                  #categories: categories,
                  #sortOrder: sortOrder,
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<List<_i7.ContentItem>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i7.ContentItem>>>(
                    this,
                    Invocation.method(#searchContent, [], {
                      #query: query,
                      #projectType: projectType,
                      #versions: versions,
                      #modLoaders: modLoaders,
                      #categories: categories,
                      #sortOrder: sortOrder,
                      #limit: limit,
                      #offset: offset,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<List<_i7.ContentItem>>>);

  @override
  _i3.Future<_i6.Result<_i7.ContentItem>> getContent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getContent, [id]),
            returnValue: _i3.Future<_i6.Result<_i7.ContentItem>>.value(
              _i8.dummyValue<_i6.Result<_i7.ContentItem>>(
                this,
                Invocation.method(#getContent, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<_i7.ContentItem>>.value(
                  _i8.dummyValue<_i6.Result<_i7.ContentItem>>(
                    this,
                    Invocation.method(#getContent, [id]),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<_i7.ContentItem>>);

  @override
  _i3.Future<_i6.Result<List<_i9.ContentVersion>>> getVersions(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getVersions, [id]),
            returnValue: _i3.Future<_i6.Result<List<_i9.ContentVersion>>>.value(
              _i8.dummyValue<_i6.Result<List<_i9.ContentVersion>>>(
                this,
                Invocation.method(#getVersions, [id]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i6.Result<List<_i9.ContentVersion>>>.value(
                  _i8.dummyValue<_i6.Result<List<_i9.ContentVersion>>>(
                    this,
                    Invocation.method(#getVersions, [id]),
                  ),
                ),
          )
          as _i3.Future<_i6.Result<List<_i9.ContentVersion>>>);
}

/// A class which mocks [DownloadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadService extends _i1.Mock implements _i10.DownloadService {
  @override
  _i3.Future<_i6.Result<void>> download(
    _i11.DownloadModel? model, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [model], {#onProgress: onProgress}),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(
                  #download,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(
                  #download,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);

  @override
  _i3.Future<_i6.Result<bool>> isDownloaded(_i11.DownloadModel? model) =>
      (super.noSuchMethod(
            Invocation.method(#isDownloaded, [model]),
            returnValue: _i3.Future<_i6.Result<bool>>.value(
              _i8.dummyValue<_i6.Result<bool>>(
                this,
                Invocation.method(#isDownloaded, [model]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i6.Result<bool>>.value(
              _i8.dummyValue<_i6.Result<bool>>(
                this,
                Invocation.method(#isDownloaded, [model]),
              ),
            ),
          )
          as _i3.Future<_i6.Result<bool>>);

  @override
  _i3.Future<_i6.Result<void>> downloadIfMissing(
    _i11.DownloadModel? model, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadIfMissing,
              [model],
              {#onProgress: onProgress},
            ),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(
                  #downloadIfMissing,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(
                  #downloadIfMissing,
                  [model],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);

  @override
  _i3.Future<_i6.Result<void>> downloadAll(
    List<_i11.DownloadModel>? models, {
    void Function(int, int?)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadAll,
              [models],
              {#onProgress: onProgress},
            ),
            returnValue: _i3.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(
                  #downloadAll,
                  [models],
                  {#onProgress: onProgress},
                ),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i6.Result<void>>.value(
              _i8.dummyValue<_i6.Result<void>>(
                this,
                Invocation.method(
                  #downloadAll,
                  [models],
                  {#onProgress: onProgress},
                ),
              ),
            ),
          )
          as _i3.Future<_i6.Result<void>>);
}
